/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DirectoryManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author apple
 */
public class CreatePanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    PersonDirectory directory;
    /**
     * Creates new form CreatePanel
     */
    public CreatePanel(JPanel usrPrcsCntnr, PersonDirectory personDirectory) {
        initComponents();
        userProcessContainer = usrPrcsCntnr;
        directory = personDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblSSNNumber = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSSNNumber = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblStreetAddressHA = new javax.swing.JLabel();
        lblCityHA = new javax.swing.JLabel();
        lblZipCodeHA = new javax.swing.JLabel();
        txtStreetAddressHA = new javax.swing.JTextField();
        txtCityHA = new javax.swing.JTextField();
        txtZipCodeHA = new javax.swing.JTextField();
        lblUnitNumberHA = new javax.swing.JLabel();
        txtUnitNumberHA = new javax.swing.JTextField();
        lblStateHA = new javax.swing.JLabel();
        txtStateHA = new javax.swing.JTextField();
        lblPhoneNumberHA = new javax.swing.JLabel();
        txtPhoneNumberHA = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lblStreetAddressWA = new javax.swing.JLabel();
        lblCityWA = new javax.swing.JLabel();
        lblZipCodeWA = new javax.swing.JLabel();
        txtStreetAddressWA = new javax.swing.JTextField();
        txtCityWA = new javax.swing.JTextField();
        txtZipCodeWA = new javax.swing.JTextField();
        lblUnitNumberWA = new javax.swing.JLabel();
        txtuniNumberWA = new javax.swing.JTextField();
        lblStateWA = new javax.swing.JLabel();
        txtStateWA = new javax.swing.JTextField();
        lblPhoneNumberWA = new javax.swing.JLabel();
        txtPhoneNumberWA = new javax.swing.JTextField();
        lblHomeAddress = new javax.swing.JLabel();
        lblWorkAddress = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(0, 204, 204));

        lblHeading.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblHeading.setText("Create Person");

        lblFirstName.setText("First name");

        lblLastName.setText("Last name");

        lblSSNNumber.setText("SSN number");

        lblAge.setText("Age");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblStreetAddressHA.setText("Street address");

        lblCityHA.setText("City");

        lblZipCodeHA.setText("Zip Code");

        txtStreetAddressHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetAddressHAActionPerformed(evt);
            }
        });

        txtCityHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityHAActionPerformed(evt);
            }
        });

        lblUnitNumberHA.setText("Unit number");

        txtUnitNumberHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitNumberHAActionPerformed(evt);
            }
        });

        lblStateHA.setText("State");

        txtStateHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateHAActionPerformed(evt);
            }
        });

        lblPhoneNumberHA.setText("Phone number");

        jLayeredPane1.setLayer(lblStreetAddressHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblCityHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblZipCodeHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtStreetAddressHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCityHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtZipCodeHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblUnitNumberHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtUnitNumberHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblStateHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtStateHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblPhoneNumberHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPhoneNumberHA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStreetAddressHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCityHA)
                    .addComponent(lblZipCodeHA)
                    .addComponent(txtZipCodeHA)
                    .addComponent(txtCityHA)
                    .addComponent(txtStreetAddressHA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUnitNumberHA)
                    .addComponent(lblStateHA)
                    .addComponent(lblPhoneNumberHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUnitNumberHA)
                    .addComponent(txtStateHA)
                    .addComponent(txtPhoneNumberHA))
                .addGap(36, 36, 36))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblUnitNumberHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnitNumberHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStateHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStateHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhoneNumberHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneNumberHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblStreetAddressHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStreetAddressHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCityHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCityHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblZipCodeHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZipCodeHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblStreetAddressWA.setText("Street address");

        lblCityWA.setText("City");

        lblZipCodeWA.setText("Zip Code");

        txtStreetAddressWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetAddressWAActionPerformed(evt);
            }
        });

        txtCityWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityWAActionPerformed(evt);
            }
        });

        lblUnitNumberWA.setText("Unit number");

        txtuniNumberWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuniNumberWAActionPerformed(evt);
            }
        });

        lblStateWA.setText("State");

        txtStateWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateWAActionPerformed(evt);
            }
        });

        lblPhoneNumberWA.setText("Phone number");

        jLayeredPane2.setLayer(lblStreetAddressWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblCityWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblZipCodeWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtStreetAddressWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtCityWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtZipCodeWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblUnitNumberWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtuniNumberWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblStateWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtStateWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblPhoneNumberWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtPhoneNumberWA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStreetAddressWA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCityWA)
                    .addComponent(lblZipCodeWA)
                    .addComponent(txtStreetAddressWA)
                    .addComponent(txtCityWA)
                    .addComponent(txtZipCodeWA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUnitNumberWA)
                    .addComponent(lblStateWA)
                    .addComponent(lblPhoneNumberWA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtuniNumberWA)
                    .addComponent(txtStateWA)
                    .addComponent(txtPhoneNumberWA))
                .addGap(36, 36, 36))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(lblUnitNumberWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtuniNumberWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStateWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStateWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhoneNumberWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneNumberWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(lblStreetAddressWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStreetAddressWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCityWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCityWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblZipCodeWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZipCodeWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblHomeAddress.setText("Home Address");

        lblWorkAddress.setText("Work Address");

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWorkAddress)
                    .addComponent(btnCreate)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHomeAddress))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(lblHeading)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastName)
                    .addComponent(lblFirstName)
                    .addComponent(lblSSNNumber)
                    .addComponent(lblAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(txtLastName)
                    .addComponent(txtSSNNumber)
                    .addComponent(txtAge))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lblHeading))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSNNumber)
                    .addComponent(txtSSNNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(lblHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblWorkAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStreetAddressHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetAddressHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetAddressHAActionPerformed

    private void txtCityHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityHAActionPerformed

    private void txtUnitNumberHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitNumberHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitNumberHAActionPerformed

    private void txtStateHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateHAActionPerformed

    private void txtStreetAddressWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetAddressWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetAddressWAActionPerformed

    private void txtCityWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityWAActionPerformed

    private void txtuniNumberWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuniNumberWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuniNumberWAActionPerformed

    private void txtStateWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateWAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String socialSecurityNumber = txtSSNNumber.getText();
        
      
        Person newPerson = directory.createPerson();
        
        try{
        newPerson.setFirstName(firstName);
        newPerson.setLastName(lastName);
        newPerson.setSocailSecurityNumber(socialSecurityNumber);
        newPerson.setAge(Integer.parseInt(txtAge.getText()));     
        }
        catch(NumberFormatException err){
            JOptionPane.showMessageDialog(jLayeredPane1, "Age should be a number.", "Invalid input", JOptionPane.ERROR_MESSAGE);
            throw err;
        }
        
        try{
            
        Address homeAddress = newPerson.getHomeAddress();
        
        homeAddress.setStreetAddress(txtStreetAddressHA.getText());
        homeAddress.setCity(txtCityHA.getText());
        homeAddress.setState(txtStateHA.getText());
        homeAddress.setZipcode(txtZipCodeHA.getText());
        homeAddress.setPhoneNumber(txtPhoneNumberHA.getText());
        homeAddress.setUnitNumber(Integer.parseInt(txtUnitNumberHA.getText()));
        
        Address workAddress = newPerson.getWorkAddress();
        
        workAddress.setStreetAddress(txtStreetAddressWA.getText());
        workAddress.setCity(txtCityWA.getText());
        workAddress.setState(txtStateWA.getText());
        workAddress.setZipcode(txtZipCodeWA.getText());
        workAddress.setPhoneNumber(txtPhoneNumberWA.getText());
        workAddress.setUnitNumber(Integer.parseInt(txtuniNumberWA.getText()));
        }
        catch(NumberFormatException error){
            JOptionPane.showMessageDialog(jLayeredPane1, "Unit number should be an integer.", "Invalid input", JOptionPane.ERROR_MESSAGE);
            throw error;
        }
        
        if (newPerson.validateInput()){
            directory.addPerson(newPerson);
        }
        else{
            JOptionPane.showMessageDialog(this, "Check the input, might be having some missing fields.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
        setAllTextfieldsClear();
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCityHA;
    private javax.swing.JLabel lblCityWA;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumberHA;
    private javax.swing.JLabel lblPhoneNumberWA;
    private javax.swing.JLabel lblSSNNumber;
    private javax.swing.JLabel lblStateHA;
    private javax.swing.JLabel lblStateWA;
    private javax.swing.JLabel lblStreetAddressHA;
    private javax.swing.JLabel lblStreetAddressWA;
    private javax.swing.JLabel lblUnitNumberHA;
    private javax.swing.JLabel lblUnitNumberWA;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JLabel lblZipCodeHA;
    private javax.swing.JLabel lblZipCodeWA;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityHA;
    private javax.swing.JTextField txtCityWA;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumberHA;
    private javax.swing.JTextField txtPhoneNumberWA;
    private javax.swing.JTextField txtSSNNumber;
    private javax.swing.JTextField txtStateHA;
    private javax.swing.JTextField txtStateWA;
    private javax.swing.JTextField txtStreetAddressHA;
    private javax.swing.JTextField txtStreetAddressWA;
    private javax.swing.JTextField txtUnitNumberHA;
    private javax.swing.JTextField txtZipCodeHA;
    private javax.swing.JTextField txtZipCodeWA;
    private javax.swing.JTextField txtuniNumberWA;
    // End of variables declaration//GEN-END:variables

    private void setAllTextfieldsClear() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtSSNNumber.setText("");
        txtAge.setText("");
        txtStreetAddressHA.setText("");
        txtStreetAddressWA.setText("");
        txtUnitNumberHA.setText("");
        txtuniNumberWA.setText("");
        txtCityHA.setText("");
        txtCityWA.setText("");
        txtZipCodeHA.setText("");
        txtZipCodeWA.setText("");
        txtStateHA.setText("");
        txtStateWA.setText("");
        txtPhoneNumberHA.setText("");
        txtPhoneNumberWA.setText("");
    }

}
