/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DirectoryManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author apple
 */
public class DirectoryPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    PersonDirectory personDirectory;

    /**
     * Creates new form DirectoryPanel
     */
    public DirectoryPanel(JPanel usrPrcsCntnr, PersonDirectory drtcy) {
        initComponents();
        userProcessContainer = usrPrcsCntnr;
        personDirectory = drtcy;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonDirectory = new javax.swing.JTable();
        lblHeading = new javax.swing.JLabel();
        txtViewDetails = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        tblPersonDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "SSN Number", "Age"
            }
        ));
        jScrollPane1.setViewportView(tblPersonDirectory);

        lblHeading.setText("Directory");

        txtViewDetails.setText("View Details");
        txtViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewDetailsActionPerformed(evt);
            }
        });

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(lblHeading))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtViewDetails)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lblHeading))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtViewDetails)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(userProcessContainer.getComponents().length-1);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPersonDirectory.getSelectedRow();
        
        if (selectedRow>=0){
            Person selectedAccount = (Person) tblPersonDirectory.getValueAt(selectedRow, 0);
            
            ViewPanel viewPanel = new ViewPanel(userProcessContainer,personDirectory,selectedAccount);
            
            JScrollPane scrollComponent;
            scrollComponent = new JScrollPane(viewPanel,JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER );

            userProcessContainer.add("ViewAccountJPanel",scrollComponent);
        
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select an entry first", "No selection made", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_txtViewDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JTable tblPersonDirectory;
    private javax.swing.JButton txtViewDetails;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPersonDirectory.getModel();
        model.setRowCount(0);
        for(Person p : personDirectory.getPeople()){
            Object[]row = new Object[4];
            
            row[0]=p;
            row[1]=p.getLastName();
            row[2]=p.getSocailSecurityNumber();
            row[3]=p.getAge();
            
            model.addRow(row);
        }
    }
}
