/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.DirectoryManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author apple
 */
public class ViewPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    PersonDirectory directory;
    Person person;

    /**
     * Creates new form ViewPanel
     */
    public ViewPanel(JPanel usrPrcsCntnr, PersonDirectory personDirectory, Person selectedPerson) {
        initComponents();
        userProcessContainer = usrPrcsCntnr;
        directory = personDirectory;
        person = selectedPerson;
        populateFields(selectedPerson);
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtSSNNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblViewAccount = new javax.swing.JLabel();
        lblRoutingNumber = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblBankName1 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblWorkAddress = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblStreetAddressHA = new javax.swing.JLabel();
        lblCityHA = new javax.swing.JLabel();
        lblZipCodeHA = new javax.swing.JLabel();
        txtStreetAddressHA = new javax.swing.JTextField();
        txtCityHA = new javax.swing.JTextField();
        txtZipCodeHA = new javax.swing.JTextField();
        lblUnitNumberHA = new javax.swing.JLabel();
        txtUnitNumberHA = new javax.swing.JTextField();
        lblStateHA = new javax.swing.JLabel();
        txtStateHA = new javax.swing.JTextField();
        lblPhoneNumberHA = new javax.swing.JLabel();
        txtPhoneNumberHA = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lblStreetAddressWA = new javax.swing.JLabel();
        lblCityWA = new javax.swing.JLabel();
        lblZipCodeWA = new javax.swing.JLabel();
        txtStreetAddressWA = new javax.swing.JTextField();
        txtCityWA = new javax.swing.JTextField();
        txtZipCodeWA = new javax.swing.JTextField();
        lblUnitNumberWA = new javax.swing.JLabel();
        txtuniNumberWA = new javax.swing.JTextField();
        lblStateWA = new javax.swing.JLabel();
        txtStateWA = new javax.swing.JTextField();
        lblPhoneNumberWA = new javax.swing.JLabel();
        txtPhoneNumberWA = new javax.swing.JTextField();
        lblHomeAddress = new javax.swing.JLabel();

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblViewAccount.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblViewAccount.setText("View Person");

        lblRoutingNumber.setText("First name");

        lblAccountNumber.setText("Last name");

        lblBankName.setText("SSN number");

        lblBankName1.setText("Age");

        lblWorkAddress.setText("Work Address");

        lblStreetAddressHA.setText("Street address");

        lblCityHA.setText("City");

        lblZipCodeHA.setText("Zip Code");

        txtStreetAddressHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetAddressHAActionPerformed(evt);
            }
        });

        txtCityHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityHAActionPerformed(evt);
            }
        });

        lblUnitNumberHA.setText("Unit number");

        txtUnitNumberHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitNumberHAActionPerformed(evt);
            }
        });

        lblStateHA.setText("State");

        txtStateHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateHAActionPerformed(evt);
            }
        });

        lblPhoneNumberHA.setText("Phone number");

        jLayeredPane1.setLayer(lblStreetAddressHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblCityHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblZipCodeHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtStreetAddressHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCityHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtZipCodeHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblUnitNumberHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtUnitNumberHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblStateHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtStateHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblPhoneNumberHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPhoneNumberHA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStreetAddressHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCityHA)
                    .addComponent(lblZipCodeHA)
                    .addComponent(txtZipCodeHA)
                    .addComponent(txtCityHA)
                    .addComponent(txtStreetAddressHA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUnitNumberHA)
                    .addComponent(lblStateHA)
                    .addComponent(lblPhoneNumberHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUnitNumberHA)
                    .addComponent(txtStateHA)
                    .addComponent(txtPhoneNumberHA))
                .addGap(36, 36, 36))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblUnitNumberHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUnitNumberHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStateHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStateHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhoneNumberHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneNumberHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblStreetAddressHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStreetAddressHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCityHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCityHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblZipCodeHA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZipCodeHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblStreetAddressWA.setText("Street address");

        lblCityWA.setText("City");

        lblZipCodeWA.setText("Zip Code");

        txtStreetAddressWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetAddressWAActionPerformed(evt);
            }
        });

        txtCityWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityWAActionPerformed(evt);
            }
        });

        lblUnitNumberWA.setText("Unit number");

        txtuniNumberWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuniNumberWAActionPerformed(evt);
            }
        });

        lblStateWA.setText("State");

        txtStateWA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateWAActionPerformed(evt);
            }
        });

        lblPhoneNumberWA.setText("Phone number");

        jLayeredPane2.setLayer(lblStreetAddressWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblCityWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblZipCodeWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtStreetAddressWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtCityWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtZipCodeWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblUnitNumberWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtuniNumberWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblStateWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtStateWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(lblPhoneNumberWA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtPhoneNumberWA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStreetAddressWA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCityWA)
                    .addComponent(lblZipCodeWA)
                    .addComponent(txtStreetAddressWA)
                    .addComponent(txtCityWA)
                    .addComponent(txtZipCodeWA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUnitNumberWA)
                    .addComponent(lblStateWA)
                    .addComponent(lblPhoneNumberWA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtuniNumberWA)
                    .addComponent(txtStateWA)
                    .addComponent(txtPhoneNumberWA))
                .addGap(36, 36, 36))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(lblUnitNumberWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtuniNumberWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStateWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStateWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhoneNumberWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneNumberWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(lblStreetAddressWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStreetAddressWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCityWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCityWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblZipCodeWA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtZipCodeWA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblHomeAddress.setText("Home Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(0, 468, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWorkAddress)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHomeAddress)
                    .addComponent(lblViewAccount)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoutingNumber)
                            .addComponent(lblBankName)
                            .addComponent(lblAccountNumber)
                            .addComponent(lblBankName1)
                            .addComponent(btnSave))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSSNNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(lblViewAccount)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoutingNumber)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccountNumber)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName)
                    .addComponent(txtSSNNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName1)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblWorkAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(110, 110, 110))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        person.setFirstName(txtFirstName.getText());
        person.setLastName(txtLastName.getText());
        person.setSocailSecurityNumber(txtSSNNumber.getText());
        person.setAge(Integer.parseInt(txtAge.getText()));
        
        Address homeAddress = person.getHomeAddress();
        homeAddress.setStreetAddress(txtStreetAddressHA.getText());
        homeAddress.setUnitNumber(Integer.parseInt(txtUnitNumberHA.getText()));
        homeAddress.setCity(txtCityHA.getText());
        homeAddress.setState(txtStateHA.getText());
        homeAddress.setZipcode(txtZipCodeHA.getText());
        homeAddress.setPhoneNumber(txtPhoneNumberHA.getText());
        
        Address workAddress = person.getWorkAddress();
        workAddress.setStreetAddress(txtStreetAddressWA.getText());
        workAddress.setUnitNumber(Integer.parseInt(txtuniNumberWA.getText()));
        workAddress.setCity(txtCityWA.getText());
        workAddress.setState(txtStateWA.getText());
        workAddress.setZipcode(txtZipCodeWA.getText());
        workAddress.setPhoneNumber(txtPhoneNumberWA.getText());
        
        populateFields(person);
        setViewMode();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(userProcessContainer.getComponents().length-1);
        Component[] panelStack = userProcessContainer.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length-1];
        DirectoryPanel directoryPanel = (DirectoryPanel) lastPanel;
        directoryPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtStreetAddressHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetAddressHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetAddressHAActionPerformed

    private void txtCityHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityHAActionPerformed

    private void txtUnitNumberHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitNumberHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitNumberHAActionPerformed

    private void txtStateHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateHAActionPerformed

    private void txtStreetAddressWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetAddressWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetAddressWAActionPerformed

    private void txtCityWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityWAActionPerformed

    private void txtuniNumberWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuniNumberWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuniNumberWAActionPerformed

    private void txtStateWAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateWAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateWAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankName1;
    private javax.swing.JLabel lblCityHA;
    private javax.swing.JLabel lblCityWA;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblPhoneNumberHA;
    private javax.swing.JLabel lblPhoneNumberWA;
    private javax.swing.JLabel lblRoutingNumber;
    private javax.swing.JLabel lblStateHA;
    private javax.swing.JLabel lblStateWA;
    private javax.swing.JLabel lblStreetAddressHA;
    private javax.swing.JLabel lblStreetAddressWA;
    private javax.swing.JLabel lblUnitNumberHA;
    private javax.swing.JLabel lblUnitNumberWA;
    private javax.swing.JLabel lblViewAccount;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JLabel lblZipCodeHA;
    private javax.swing.JLabel lblZipCodeWA;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityHA;
    private javax.swing.JTextField txtCityWA;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumberHA;
    private javax.swing.JTextField txtPhoneNumberWA;
    private javax.swing.JTextField txtSSNNumber;
    private javax.swing.JTextField txtStateHA;
    private javax.swing.JTextField txtStateWA;
    private javax.swing.JTextField txtStreetAddressHA;
    private javax.swing.JTextField txtStreetAddressWA;
    private javax.swing.JTextField txtUnitNumberHA;
    private javax.swing.JTextField txtZipCodeHA;
    private javax.swing.JTextField txtZipCodeWA;
    private javax.swing.JTextField txtuniNumberWA;
    // End of variables declaration//GEN-END:variables

    private void populateFields(Person selectedPerson) {
        txtFirstName.setText(selectedPerson.getFirstName());
        txtLastName.setText(selectedPerson.getLastName());
        txtSSNNumber.setText(selectedPerson.getSocailSecurityNumber());
        txtAge.setText(Integer.toString(selectedPerson.getAge()));
        Address homeAddress = selectedPerson.getHomeAddress();
        Address workAddress = selectedPerson.getWorkAddress();
        txtStreetAddressHA.setText(homeAddress.getStreetAddress());
        txtStreetAddressWA.setText(workAddress.getStreetAddress());
        txtUnitNumberHA.setText(Integer.toString(homeAddress.getUnitNumber()));
        txtuniNumberWA.setText(Integer.toString(workAddress.getUnitNumber()));
        txtCityHA.setText(homeAddress.getCity());
        txtCityWA.setText(workAddress.getCity());
        txtPhoneNumberHA.setText(homeAddress.getPhoneNumber());
        txtPhoneNumberWA.setText(workAddress.getPhoneNumber());
        txtZipCodeHA.setText(homeAddress.getZipcode());
        txtZipCodeWA.setText(homeAddress.getZipcode());
        txtStateHA.setText(homeAddress.getState());
        txtStateWA.setText(workAddress.getState());
        selectedPerson.setHomeAddress(homeAddress);
        selectedPerson.setWorkAddress(workAddress);
    }
    
    private void setViewMode(){
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        disableTextFields();
    }
    
    private void setEditMode(){
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        enableTextFields();
    }
    
    private void disableTextFields(){
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtSSNNumber.setEnabled(false);
        txtAge.setEnabled(false);
        txtStreetAddressHA.setEnabled(false);
        txtStreetAddressWA.setEnabled(false);
        txtUnitNumberHA.setEnabled(false);
        txtuniNumberWA.setEnabled(false);
        txtCityHA.setEnabled(false);
        txtCityWA.setEnabled(false);
        txtPhoneNumberHA.setEnabled(false);
        txtPhoneNumberWA.setEnabled(false);
        txtZipCodeHA.setEnabled(false);
        txtZipCodeWA.setEnabled(false);
        txtStateHA.setEnabled(false);
        txtStateWA.setEnabled(false);
    }
    
    private void enableTextFields(){
        txtFirstName.setEnabled(true);
        txtLastName.setEnabled(true);
        txtSSNNumber.setEnabled(true);
        txtAge.setEnabled(true);
        txtStreetAddressHA.setEnabled(true);
        txtStreetAddressWA.setEnabled(true);
        txtUnitNumberHA.setEnabled(true);
        txtuniNumberWA.setEnabled(true);
        txtCityHA.setEnabled(true);
        txtCityWA.setEnabled(true);
        txtPhoneNumberHA.setEnabled(true);
        txtPhoneNumberWA.setEnabled(true);
        txtZipCodeHA.setEnabled(true);
        txtZipCodeWA.setEnabled(true);
        txtStateHA.setEnabled(true);
        txtStateWA.setEnabled(true);
    }

}
